#!/bin/sh
set -e

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "$1" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

modprobe dm_verity || true
modprobe dm_mod || true

VERITY_DATA="/dev/disk/by-partlabel/verityrootfs"
VERITY_HASH="/dev/disk/by-partlabel/verityhash"
VERITY_NAME="verityroot"

# Filled in during image build.
ROOT_HASH="5299c5a0d10ffd6b5c06df794e227360842a23f8dc26db2a5f8938f75560ea6f"

log_begin_msg "Opening dm-verity root"
veritysetup open "$VERITY_DATA" "$VERITY_NAME" "$VERITY_HASH" "$ROOT_HASH"
log_end_msg
